// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/healthcheck": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/healthcheck";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/healthcheck.tsx": {
    id: "routes/healthcheck";
    page: "/healthcheck";
  };
};

type RouteModules = {
  root: typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/./routes/_index.tsx");
  "routes/healthcheck": typeof import("./app/./routes/healthcheck.tsx");
};
