packages:
  - config/*
  - packages/*
  - apps/*

catalog:
  "@t3-oss/env-core": 0.13.10
  "@types/source-map-support": 0.5.10
  chalk: 5.6.2
  cross-env: 10.1.0
  dotenv: 17.3.1
  glob: 13.0.6
  isbot: 5.1.35
  rimraf: 6.1.3
  source-map-support: 0.5.21

catalogs:
  drizzle:
    drizzle-kit: 0.31.9
    drizzle-orm: 0.45.1
  hono:
    hono: 4.12.2
    hono-rate-limiter: ^0.5.0
    react-router-hono-server: 2.25.0
    remix-hono: ^0.0.18
  postgresql:
    "@types/pg": 8.16.0
    pg: 8.19.0
  prisma:
    "@prisma/adapter-better-sqlite3": 6.18.0
    "@prisma/adapter-libsql": 6.18.0
    "@prisma/adapter-pg": 6.18.0
    "@prisma/client": 6.18.0
    prisma: 6.18.0
  react-router:
    "@react-router/dev": 7.13.1
    "@react-router/fs-routes": 7.13.1
    "@react-router/node": 7.13.1
    "@react-router/remix-routes-option-adapter": 7.13.1
    react-router: 7.13.1
    react-router-dom: 7.13.1
  react19:
    react: 19.2.4
    react-dom: 19.2.4
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3
  sentry:
    "@sentry/profiling-node": 10.40.0
    "@sentry/react-router": 10.40.0
    "@sentry/vite-plugin": 4.6.1
  sqlite:
    "@libsql/client": 0.17.0
  storybook:
    "@storybook/addon-docs": 10.2.12
    "@storybook/addon-onboarding": 10.2.12
    "@storybook/builder-vite": 10.2.12
    "@storybook/react-vite": 10.2.12
    eslint-plugin-storybook: 10.2.12
    storybook: 10.2.12
  tailwindcss:
    "@tailwindcss/typography": 0.5.19
    "@tailwindcss/vite": 4.2.1
    prettier-plugin-tailwindcss: 0.7.2
    tailwind-merge: 3.5.0
    tailwindcss: 4.2.1
    tw-animate-css: 1.4.0
  typescript:
    tsup: 8.5.1
    tsx: 4.21.0
    typescript: 5.9.3
