packages:
  - "config/*"
  - "packages/*"
  - "apps/*"

catalog:
  isbot: 5.1.31
  chalk: 5.6.2
  cross-env: 10.1.0
  dotenv: 17.2.3
  "@t3-oss/env-core": 0.13.8
  source-map-support: 0.5.21
  "@types/source-map-support": 0.5.10
  glob: 11.0.3
  rimraf: 6.0.1

catalogs:
  typescript:
    typescript: 5.9.3
    tsx: 4.20.6
    tsup: 8.5.0
  react-router:
    react-router: ^7.9.3
    react-router-dom: ^7.9.3
    "@react-router/node": ^7.9.3
    "@react-router/dev": ^7.9.3
    "@react-router/remix-routes-option-adapter": ^7.9.3
    "@react-router/fs-routes": ^7.9.3
  react19:
    react: 19.2.0
    react-dom: 19.2.0
    "@types/react": 19.2.2
    "@types/react-dom": ^19.1.9
  hono:
    hono: 4.10.4
    hono-rate-limiter: ^0.4.2
    react-router-hono-server: 2.22.0
    remix-hono: ^0.0.18
  sentry:
    "@sentry/react-router": 10.22.0
    "@sentry/profiling-node": 10.22.0
    "@sentry/vite-plugin": 4.6.0
  tailwindcss:
    tailwindcss: 4.1.16
    tw-animate-css: 1.4.0
    "@tailwindcss/vite": 4.1.16
    "@tailwindcss/typography": 0.5.19
    tailwind-merge: 3.3.1
    prettier-plugin-tailwindcss: 0.7.1
  storybook:
    storybook: 10.0.1
    "@storybook/addon-docs": 10.0.1
    "@storybook/addon-onboarding": 10.0.1
    "@storybook/react-vite": 10.0.1
    "@storybook/builder-vite": 10.0.1
    eslint-plugin-storybook: 10.0.1
  prisma:
    prisma: 6.18.0
    "@prisma/adapter-better-sqlite3": 6.18.0
    "@prisma/adapter-libsql": 6.18.0
    "@prisma/client": 6.18.0
