packages:
  - config/*
  - packages/*
  - apps/*

catalog:
  "@t3-oss/env-core": 0.13.8
  "@types/source-map-support": 0.5.10
  chalk: 5.6.2
  cross-env: 10.1.0
  dotenv: 17.2.3
  glob: 11.0.3
  isbot: 5.1.32
  rimraf: 6.1.2
  source-map-support: 0.5.21

catalogs:
  drizzle:
    drizzle-kit: 0.31.7
    drizzle-orm: 0.44.7
  hono:
    hono: 4.10.7
    hono-rate-limiter: ^0.4.2
    react-router-hono-server: 2.22.0
    remix-hono: ^0.0.18
  postgresql:
    "@types/pg": 8.15.6
    pg: 8.16.3
  prisma:
    "@prisma/adapter-better-sqlite3": 6.18.0
    "@prisma/adapter-libsql": 6.18.0
    "@prisma/adapter-pg": 6.18.0
    "@prisma/client": 6.18.0
    prisma: 6.18.0
  react-router:
    "@react-router/dev": 7.10.0
    "@react-router/fs-routes": 7.10.0
    "@react-router/node": 7.10.0
    "@react-router/remix-routes-option-adapter": 7.10.0
    react-router: 7.10.0
    react-router-dom: 7.10.0
  react19:
    "@types/react": 19.2.7
    "@types/react-dom": ^19.1.9
    react: 19.2.1
    react-dom: 19.2.1
  sentry:
    "@sentry/profiling-node": 10.27.0
    "@sentry/react-router": 10.27.0
    "@sentry/vite-plugin": 4.6.1
  sqlite:
    "@libsql/client": 0.15.15
  storybook:
    "@storybook/addon-docs": 10.0.8
    "@storybook/addon-onboarding": 10.0.8
    "@storybook/builder-vite": 10.0.8
    "@storybook/react-vite": 10.0.8
    eslint-plugin-storybook: 10.0.8
    storybook: 10.0.8
  tailwindcss:
    "@tailwindcss/typography": 0.5.19
    "@tailwindcss/vite": 4.1.17
    prettier-plugin-tailwindcss: 0.7.1
    tailwind-merge: 3.4.0
    tailwindcss: 4.1.17
    tw-animate-css: 1.4.0
  typescript:
    tsup: 8.5.1
    tsx: 4.20.6
    typescript: 5.9.3
