packages:
  - "config/*"
  - "packages/*"
  - "apps/*"

catalogs:
  hono:
    hono: 4.10.2
    hono-rate-limiter: ^0.4.2
    react-router-hono-server: 2.21.0
    remix-hono: ^0.0.18
  sentry:
    "@sentry/react-router": 10.21.0
    "@sentry/profiling-node": 10.21.0
    "@sentry/vite-plugin": 4.5.0
